[package]
name = "tower-sesh-benches"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
rmp-serde = "1.3.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[[bench]]
name = "record"
path = "src/record.rs"
harness = false
